name: particles_network
description: >
  A performant and customizable interactive particle network widget for Flutter.
  Ideal for background animations, landing pages, and visual effects.
version: 1.5.4
repository: https://github.com/abod8639/Particles_Network.git
homepage: https://github.com/abod8639/Particles_Network

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
