name: particles_network
description: >
  A performant and customizable interactive particle network widget for Flutter.
  Ideal for background animations, landing pages, and visual effects.
version: 1.7.2
repository: https://github.com/abod8639/Particles_Network.git
homepage: https://github.com/abod8639/Particles_Network

environment:
  sdk: ^3.7.2
  flutter: 3.32.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.0.0
  test: ^1.16.0
  build_runner: ^2.4.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

screenshots:
  - description: The equatable package logo.
    path: assets/Picsart_25-05-10_12-57-34-680.png